### PR TITLE
Add API keys page navigation sidebar

### PR DESCRIPTION
**Pull request by benwerner01**
## 🌟 What is the purpose of this PR?

This PR converts the existing `/settings/api-keys` page to a settings panel consistent with the layout of the billing settings panel (with a sidebar).

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203623179643287/1203781148500080/f) _(internal)_

## 📜 Does this require a change to the docs?

Not that I'm aware of.

## ⚠️ Known issues

- Because we need to support the previous API keys page at `/settings/api-keys` (as the billing feature flag remains disabled in production), we can't delete the `api-keys.page.ts` file outright. Therefore the panel is currently hosted at `/settings/api-keys-panel`.

## 🛡 What tests cover this?

Manual testing.

## ❓ How to test this?

1. Enable the billing feature flag
2. Navigate to `/settings/api-keys-panel` when logged in

## 📹 Demo

image

### CODE REVIEW

**Review by nonparibus — CHANGES_REQUESTED** [review]
@benwerner01 Can "Api Keys" in the sidebar please be changed to read "API Keys"?

Separately, please can you ensure the alignment is flush? Currently the sidebar nav and header above are misaligned (see below).

Capture 2023-02-24 at 01 33 51@2x

**Comment by benwerner01** [comment]
> @benwerner01 Can "Api Keys" in the sidebar please be changed to read "API Keys"?
> 
> Separately, please can you ensure the alignment is flush? Currently the sidebar nav and header above are misaligned (see below).
> 
> Capture 2023-02-24 at 01 33 51@2x

Thanks for spotting, done in https://github.com/blockprotocol/blockprotocol/pull/1029/commits/11ffb062450da8fafcc827cea38af3dff9e002b3

**Comment by benwerner01** [comment]
> @benwerner01 Can "Api Keys" in the sidebar please be changed to read "API Keys"?
> 
> Separately, please can you ensure the alignment is flush? Currently the sidebar nav and header above are misaligned (see below).

Yes, done in https://github.com/blockprotocol/blockprotocol/pull/1029/commits/435ccccbcc5ebfe0fe6757933e8ca29f426e7474 and https://github.com/blockprotocol/blockprotocol/pull/1029/commits/11ffb062450da8fafcc827cea38af3dff9e002b3

**Comment by nonparibus** [comment]
Thanks, visually looks good to me 👍 Nothing blocking from my side.

**Review by CiaranMn — APPROVED** [review]

**Review by nonparibus — APPROVED** [review]

**Pull request merged**
