### PR TITLE
[BP-9]: Move `spec` out of `docs`, continue to share spec/docs sidebar

### PR DESCRIPTION
**Pull request by gitstart-blockprotocol**
🌟 What is the purpose of this PR?
---
Move `spec` out of `docs`, continue to share spec/docs sidebar

🔗  Related links
---
- [Github](https://github.com/blockprotocol/blockprotocol/issues/1186)

❓How to test this?
---
https://www.loom.com/share/6bbd4d2c51044c8a82b8dce08970387f

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### CODE REVIEW

**Review by nonparibus — DISMISSED** [review]
One drive-by suggestion around redirects here. There is a function issue with the new `/spec` and `/roadmap` pages whereby the left-hand sidebar found on `/docs` **is** correctly included, but the behavior of the adjoining header **is not**. This is immediately visible when clicking onto the roadmap/spec in the sidebar, having been on another page previously.

On the `/spec`, `/roadmap` and `/docs` we want the header to be omnipresent, unlike on the rest of the site where it disappears when it is set to disappear when the user scrolls (maximizing vertical real-estate). Please can we we mirror the behavior of the header on `/docs` on these new `/roadmap` and `/spec` pages? Thank you. **We should not alter the header behavior on other pages (e.g. `/wordpress`, `/about`, etc.) where it should remain as-is.**

**Correct:**
Correct header scroll on docs,spec,roadmap

**Incorrect (current):**
Incorrect header scroll

**Comment by gitstart-blockprotocol** [comment]
> One drive-by suggestion around redirects here. There is a function issue with the new `/spec` and `/roadmap` pages whereby the left-hand sidebar found on `/docs` **is** correctly included, but the behavior of the adjoining header **is not**. This is immediately visible when clicking onto the roadmap/spec in the sidebar, having been on another page previously.
> 
> On the `/spec`, `/roadmap` and `/docs` we want the header to be omnipresent, unlike on the rest of the site where it disappears when it is set to disappear when the user scrolls (maximizing vertical real-estate). Please can we we mirror the behavior of the header on `/docs` on these new `/roadmap` and `/spec` pages? Thank you. **We should not alter the header behavior on other pages (e.g. `/wordpress`, `/about`, etc.) where it should remain as-is.**
> 
> **Correct:** Correct header scroll on docs,spec,roadmap
> 
> **Incorrect (current):** Incorrect header scroll

Hello @nonparibus. Please, could you help give a more comprehensive explanation?

**Comment by gitstart-blockprotocol** [comment]
@nonparibus, The comments have been addressed. Thank you

**Review by nathggns — APPROVED** [review]

**Review by nathggns — CHANGES_REQUESTED** [review]
Playwright tests need updating in order to make this pass – see the failed required check

**Comment by gitstart-blockprotocol** [comment]
> Playwright tests need updating in order to make this pass – see the failed required check

@nathggns, Fixed

**Comment by nathggns** [comment]
@gitstart-blockprotocol Required checks still seem to be failing - can you take a look?

**Comment by gitstart-blockprotocol** [comment]
Hello @nathggns, the test that displays failing on the `integrations/docs.test.ts` 
```
await expect(page.locator("text=PreviousFAQs >> a")).toBeVisible();

await expect(page.locator("text=PreviousFAQs >> a")).toHaveAttribute(
  "href",
  "/docs/faq",
);
```

Screenshot 2023-04-17 at 18 33 40

From the image, it shows the text link to be API, we didn't implement this feature but should we go ahead and fix it?

**Comment by nathggns** [comment]
@gitstart-blockprotocol the tests need updating because the order of pages have changed, so the "previous" page when on spec is now different, which is why the test is failing.

**Comment by gitstart-blockprotocol** [comment]
@nathggns, Feedback addressed

**Review by nathggns — APPROVED** [review]

**Pull request merged**
