### PR TITLE
Fix voting section application name input responsiveness

### PR DESCRIPTION
**Pull request by luisbettencourt**
## 🌟 What is the purpose of this PR?

This PR changes the placeholder of the application name input in the voting section so that it doesn't overflow the element.

## 📹 Demo

Before:

image

After:

image

### CODE REVIEW

**Review by kachkaev — DISMISSED** [review]
Random idea:

```
What application would you like to use the Þ
in? 👀
```
↓
```
What app would you like to use the Þ in? 👀
```

**Comment by nonparibus** [comment]
LGTM. I second Alex's suggestion, though, as at certain smaller screen sizes it may prevent the text otherwise breaking where it otherwise needn't.

**Comment by luisbettencourt** [comment]
Included @kachkaev's suggestion and also the modal border color fix in this PR.

**Comment by nonparibus** [comment]
Just spotted an additional bug (I think introduced in https://github.com/blockprotocol/blockprotocol/pull/859, although it may possible predate).

The section doesn't resize to provide room for validation errors that may occur on the form input, which can result in the 'back' link sliding out of view.

See screenshot attached

Capture 2022-12-21 at 23 56 39@2x

**Review by CiaranMn — APPROVED** [review]

**Review by CiaranMn — APPROVED** [review]

**Review by CiaranMn — APPROVED** [review]

**Review by CiaranMn — APPROVED** [review]

**Pull request merged**
