### PR TITLE
Implement JSON editor in "Block Properties" tab

### PR DESCRIPTION
**Pull request by yusufkinatas**
## 🌟 What is the purpose of this PR?

- Make block data tab's content on editable & highlight it's syntax

_Created `JsonEditor` as a component, not for reusability, but to keep [block-data-tab-panels.tsx](https://github.com/blockprotocol/blockprotocol/blob/f857dcd25cd16f5af8d55e09b4d69df51bf45015/site/src/components/pages/hub/block-data-tab-panels.tsx) short & clean. If we need to have a generic `CodeEditor` component in future, we can modify `JsonEditor` to work more independently as a component._

## 🔗 Related links
[Asana task](https://app.asana.com/0/1200211978612931/1202732542284286/f) (internal)

## ❓ How to test this?

1.  Checkout the branch / view the deployment
1.  Open any block from block hub
2. Try editing the block data

## 📹 Demo

https://user-images.githubusercontent.com/39553853/184159884-b570e196-838d-45dd-b8af-bb1fe73d5d51.mov

### CODE REVIEW

**Comment by nathggns** [comment]
Hey @yusufkinatas – thank you for this. Could you please check this is working as expected in Safari? I'm not certain it is

https://www.loom.com/share/961da75179d54c0eab6fa323e5735e81

**Comment by yusufkinatas** [comment]
@nathggns Definitely not working as expected on Safari, let me have a look at it 👀

**Comment by nathggns** [comment]
@yusufkinatas could you convert this PR to a draft?

**Comment by yusufkinatas** [comment]
> Hey @yusufkinatas – thank you for this. Could you please check this is working as expected in Safari? I'm not certain it is
> 
> https://www.loom.com/share/961da75179d54c0eab6fa323e5735e81

@nathggns Addressed this at https://github.com/blockprotocol/blockprotocol/pull/496/commits/12bf2ea0000b45c7d54efa98daf4989c99f65ca8.  It was related with safari-chrome acting different with text-wrapping of text-area

**Comment by nathggns** [comment]
@yusufkinatas I'm afraid there's also something strange going on on Firefox https://www.loom.com/share/57c217ff35a84da9bd9b1792773f2cf3 – could you take a look?

**Comment by yusufkinatas** [comment]
> @yusufkinatas I'm afraid there's also something strange going on on Firefox https://www.loom.com/share/57c217ff35a84da9bd9b1792773f2cf3 – could you take a look?

@nathggns addressed this at https://github.com/blockprotocol/blockprotocol/pull/496/commits/d027252b7298d0d3c2445052d766c0e4e78063d0, it was pretty annoying to deal with :D

**Review by nathggns — DISMISSED** [review]

**Comment by nathggns** [comment]
Well done @yusufkinatas

**Review by nathggns — APPROVED** [review]

**Comment by nathggns** [comment]
Well done @yusufkinatas

**Pull request merged**
