### PR TITLE
Replace hiring banner with 0.3 announcement banner

### PR DESCRIPTION
**Pull request by luisbettencourt**
## 🌟 What is the purpose of this PR?

Implements a new banner at the top of all pages (except `/wordpress`).

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203363157432084/1203488186089101/f) _(internal)_

## 🚫 Blocked by

- [x] https://github.com/blockprotocol/blockprotocol/pull/837
- [x] https://github.com/blockprotocol/blockprotocol/pull/849

## 📹 Demo

image

### CODE REVIEW

**Comment by nonparibus** [comment]
@luisbettencourt Can we have the page open in the same time (graceful transition) rather than new tab? Ty

**Comment by nonparibus** [comment]
Can we also reduce the height of the banner slightly to ~70px?

**Comment by nonparibus** [comment]
We also want to link directly to the 0.3 section on the WP landing page via an anchor link, so users scroll straight down to it.

**Review by kachkaev — APPROVED** [review]

**Review by kachkaev — APPROVED** [review]

**Review by kachkaev — DISMISSED** [review]
Playwright tests 🙏

**Review by nonparibus — APPROVED** [review]

**Comment by kachkaev** [comment]
@nonparibus @luisbettencourt we need to fix Playwright tests which are now failing for `main`. Something is wrong with the dashboard: https://github.com/blockprotocol/blockprotocol/actions/runs/3716126696/jobs/6302096758

```
Running 34 tests using 1 worker
···××T················°·············

  1) [integration-firefox] › integration/api-keys.test.ts:5:1 › API key page should generate a valid key 

    Test timeout of 30000ms exceeded.

    locator.click: Target closed
    =========================== logs ===========================
    waiting for selector "a >> text=Create new key"
    ============================================================

      39 |   await expect(tableWithKeys).not.toBeVisible();
      40 |
    > 41 |   await page.locator("a >> text=Create new key").click();
         |                                                  ^
      42 |
      43 |   await keyNameInput.click();
      44 |   await keyNameInput.press("Enter");

        at file:///home/runner/work/blockprotocol/blockprotocol/apps/site/tests/integration/api-keys.test.ts:41:50

    Pending operations:
      - locator.click at tests/integration/api-keys.test.ts:41:50
```

**Pull request merged**
