### PR TITLE
Restore text blocks to hub

### PR DESCRIPTION
**Pull request by CiaranMn**
This PR updates the commit for blocks to account for updates to text blocks, and restores text blocks to the hub.

Text blocks on the hub now work as we introduced the hook service to mock-block-dock in #656 (mock-block-dock is what renders blocks in the hub, and acts as an embedding application)

How to test:
1. https://blockprotocol-hsvoiwjjr.stage.hash.ai/@hash/blocks/paragraph
2. https://blockprotocol-hsvoiwjjr.stage.hash.ai/@hash/blocks/callout
3. https://blockprotocol-hsvoiwjjr.stage.hash.ai/@hash/blocks/header 

### Known issues

The formatting toolbar can be hidden on the top line as it is outside the iFrame's boundary. We could add arbitrary padding to the top of the iFrame to give blocks a bit more breathing room to fix this in follow up.

---

  - https://app.asana.com/0/0/1202510130282422

### CODE REVIEW

**Review by nonparibus — CHANGES_REQUESTED** [review]
Text block listings in the Hub look good to me. We seem to have wound up with this, however.
Capture 2022-10-24 at 16 03 04@2x

**Comment by nonparibus** [comment]
Clicking between the header tabs on https://blockprotocol-prm6y7xe9.stage.hash.ai/@hash/blocks/header seems to result in them not always consistently appearing. Very weird. @CiaranMn Can you take a look?

**Comment by CiaranMn** [comment]
Putting back into draft until the issue with the header block is fixed

**Review by nonparibus — APPROVED** [review]
I'd like to revise how we show variants of blocks in the Hub at some point, but this PR itself does what it set out to. Thanks for this!

**Pull request merged**
