### PR TITLE
Update `Þ Hub` homepage

### PR DESCRIPTION
**Pull request by nathggns**
## 🌟 What is the purpose of this PR?

This redesigns the hub home page to match the new design, including showing all types on the page 

Services are featured flagged with a `HUB_SERVICES_ENABLED` in `hub.page.tsx`, as not actually implemented in terms of fetching and displaying them, but the UI is there

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203358502199087/1203767287750307/f) _(internal)_

## 🚫 Blocked by

N/A

## 🔍 What does this change?

- New background for footer on hub page
- Removed loading state for hub cards as data resolved on server
- Removed coming soon hub card
- New copy for footer on hub page
- Renamed `BinaryIcon` to `BinarySharpIcon` as there is a new binary regular icon in use, which I'm implementing using `IconDefinition` from fontawesome
- New `?type=` URL filter for blocks/types to change what type of item is displayed in the hub
- Redesigned hub page with new `HubList` component which displays the listing grid
- New `getFeaturedBlocks` function which returns some hard coded featured blocks
- 

## 📜 Does this require a change to the docs?

N/A

## ⚠️ Known issues

No copy under `Types` title (see below) – discussion at https://hashintel.slack.com/archives/C02LG39FJAU/p1676980148065219

image

## 🐾 Next steps

- Filters 
- Services
- X weekly downloads
- Last updated at for types
- Search 
- Pagination

## 🛡 What tests cover this?

N/A

## ❓ How to test this?

Open `/hub` and visually check

### CODE REVIEW

**Comment by CiaranMn** [comment]
@nonparibus can you do a visual check on this before code review please

**Comment by nonparibus** [comment]
Capture 2023-02-22 at 13 14 45@2x

**Comment by nonparibus** [comment]
@CiaranMn @nathggns I have dropped comments on the Vercel preview deployment: https://blockprotocol-5a0ptywb1.stage.hash.ai/hub

**Review by CiaranMn — COMMENTED** [review]
@nathggns had a quick play – when you switch back between types and blocks, some blocks get repeated the top of the list. Assume something to do with state or array indexing

Of David's comments, I think we can do animation and gradient changes in follow up – unless you think they're quick can you create follow up tickets for them?

**Comment by nathggns** [comment]
> some blocks get repeated the top of the list. Assume something to do with state or array indexing

This bug is not present locally, but can repro. That's weird.

**Comment by nathggns** [comment]
Further discussion RE the bug at https://hashintel.slack.com/archives/C02LG39FJAU/p1677470666170939 – think it's a staging setup problem, not a bug in my code

**Comment by nathggns** [comment]
@nonparibus most changes actioned – follow up ticket for others at https://app.asana.com/0/1203623179643290/1204062182948733/f (internal)

**Review by nonparibus — CHANGES_REQUESTED** [review]
@nathggns Dropped Vercel comments re: missed comment, and a few v small additional things. Have also expanded the list on the Asana ticket to reflect other open comments (which I have resolved in Vercel, to clear up the view)

@CiaranMn @luisbettencourt @kachkaev This is otherwise ready for code review.

**Comment by nathggns** [comment]
Think I need to fix tests

**Comment by nathggns** [comment]
@nonparibus when you come to check this again, be mindful that featured blocks won't show as expected. This is a staging data issue. https://hashintel.slack.com/archives/C02LG39FJAU/p1677577293777029

**Review by CiaranMn — APPROVED** [review]

**Pull request merged**
