### PR TITLE
Add @shinypb/emoji-trading-cards.json

### PR DESCRIPTION
**Pull request by shinypb**
Hello! Am I doing this right? 😅 

https://blockprotocol.org/docs/publishing-blocks#block-hub

### CODE REVIEW

**Comment by CiaranMn** [comment]
Love it @shinypb! You are absolutely doing it right. 😁 

We'd love any feedback on how you got on with reading the docs and building a block - either here, [Discord](https://blockprotocol.org/discord), or in a [discussion](https://github.com/blockprotocol/blockprotocol/discussions).

There are a couple of additions you could make to the `package.json` in your source to better show off your block on blockprotocol.org - we will add these to the documentation and to the template, as they're missing at the moment:

1. You could add an `image` to the `blockprotocol` object (in `package.json`), to act as the preview image when the block is viewed on the hub (or elsewhere) - we provide this fallback otherwise
Screenshot 2022-02-03 at 12 06 48

2. You could add an `examples` array to the `blockprotocol` object, which contains a single object giving an example of the data that is passed to your block - this will be automatically used to populate the data source on the blocks page. For example, if you added `{ examples: [{ "emojiName": "+1" }] }` your block would look like this on the page:
Screenshot 2022-02-03 at 12 10 46

[Here's an example](https://github.com/hashintel/hash/blob/main/packages/blocks/code/package.json#L71) of a package.json with those values.

Neither of these are required, and I'm happy to get this merged and deployed without them, but thought I'd mention as they're somewhat obscure at the moment. 

Thanks for contributing - looking forward to seeing emoji-trading-cards in the wild 😅

**Comment by shinypb** [comment]
Thanks, Ciaran! I'm about to head out on a road trip but I'll get back to you next week with my thoughts. I'm really excited to see where Block Protocol ends up!

**Comment by shinypb** [comment]
Howdy, @CiaranMn! This PR is ready for a look, and here's my feedback, as promised:

Some thoughts on the Block Protocol development & publishing process, in no particular order.

1. Development was about as straightforward as one could hope for, especially from a 1.0 release—it's hard to beat "write a React component; here's your boilerplate" for simplicity. That being said, I would love to eventually see the development environment mature into something more like Storybook: let me switch between the example data in package.json:blockprotocol/examples directly within my web browser.

2. I really wanted a way to build a standalone, plain HTML/JS version of my block so I could throw it up on my personal web site, in lieu of being able to publish it on the Block Hub immediately. I ultimately ended up writing my own webpack config to do it; a simple `yarn build` command would've been very welcome. I'd normally offer to contribute my efforts here back to the project, but getting corporate approval to sign the contributor agreement is a bit of a pain for me at the moment.

3. Publishing on the Block Hub has been more complex than expected. The biggest barrier to entry is the contributor agreement, which I see has already been addressed, but having the flow be entirely manual is also a source of friction. I'm sure this will all have a web UI at some point, but a bit of command line automation in the meantime would go a long way.

I'd have really appreciated a `yarn publish` command (or similar) that would prompt me for any missing data (e.g. "image on the blockprotocol object in package.json), create a commit if necessary, push to a branch, and open the GitHub pull request page in my browser.

4. I really wish there was a way to see a simulated version of my block's Block Hub page locally.

**Comment by CiaranMn** [comment]
Thanks very much, @shinypb - very useful feedback! 

A Storybook-like environment for developing blocks is a great idea which we'll work towards.

You're right that the publishing flow is a cumbersome early version, and we will be adding a web UI to make it all a lot easier.

In the short-term, we will add commands to:
- build a standalone bundle for blocks
- check block metadata and automate as many publishing steps as possible

Thank you for these suggestions. :star:

There are two ways to see a simulated version of your block's Block Hub page locally - appreciate this is a bit of work and we'll think about how we can make this easier (and document it):

**In development**
1. add the JSON for your block to your fork of this repo, in `hub/` (you've already done this)
2. optionally delete the other folders (e.g. `hub/@hash`) to speed up build time
3. run `cd site && yarn build-blocks && yarn dev`
4. visit `http://localhost:3000/hub`

**Once a PR is up and workflows have been approved / run**
1. Look for vercel bot notices and visit the preview deployment - the latest here being at https://blockprotocol-4hxtk2w8k-hashintel.vercel.app/hub 

At the moment, your block still has the fallback preview image as you have the link under `preview` rather than `image` - a good advertisement for your suggested publish-automation command. Could you please update this and then let me know and we'll get it merged?

**Comment by shinypb** [comment]
Whoops, good catch & thank you. Should be all good now:
https://github.com/shinypb/emoji-trading-cards/blob/main/package.json#L69

Thanks for the hub preview instructions. I'll give these a whirl next time I'm iterating on the block. :+1:

**Review by CiaranMn — APPROVED** [review]

**Comment by CiaranMn** [comment]
And [it's live](https://blockprotocol.org/@shinypb/emoji-trading-cards) 🎉 

Thanks @shinypb for the first ever user-contributed Block Protocol block!

**Pull request merged**
