### PR TITLE
Add GPT-4 monthly free tokens

### PR DESCRIPTION
**Pull request by benwerner01**
## 🌟 What is the purpose of this PR?

This PR adds the GPT-4 monthly free tokens to the existing BP pages.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1204260760205594/1204502471509788/f) _(internal)_

## 🚫 Blocked by

- [x] merging https://github.com/hashintel/internal-api/pull/97

## 🔍 What does this change?

- regenerates the internal API client from the `bw/gpt-4` branch on the internal API repo

## 🚀 Has this modified a publishable library?

This PR:

- [ ] modifies an **npm**-publishable library and **I have added a changeset file(s)**
- [ ] modifies a **Cargo**-publishable library and **I have amended the version**
- [ ] modifies a **Cargo**-publishable library, but **it is not yet ready to publish**
- [ ] modifies a **block** that will need publishing
- [x] does not modify any publishable blocks or libraries
- [ ] I am unsure / need advice

## 🛡 What tests cover this?

None

## 📹 Demo

Changes to the pricing page:

image

Changes to the upgrade page for "free"/"hobby" users:

image

Changes to the upgrade page for "pro" users:

image

### CODE REVIEW

**Comment by Alfred-Mountfield** [comment]
Just flagging the demo screenshots (at time of writing this comment) in the PR description are seemingly outdated. They contain strange things such as this additional "Mapbox": 
image

However I do not see it in the preview deployment

**Comment by benwerner01** [comment]
> They contain strange things such as this additional "Mapbox"

@Alfred-Mountfield thanks for spotting, not sure when that slipped in. Have fixed that in https://github.com/blockprotocol/blockprotocol/pull/1282/commits/c52e3a3d0504134b769909300732d0342e9efc72. Are there other issues you spotted in the screenshots?

> Just flagging the demo screenshots (at time of writing this comment) in the PR description are seemingly outdated. [...] However I do not see it in the preview deployment

I'm not able to replicate this, for me the deployment reflect the up-to-date state:

image

**Comment by Alfred-Mountfield** [comment]
> I'm not able to replicate this, for me the deployment reflect the up-to-date state:

I think you might have mistaken my previous message, I said the screenshots in the PR description are out of date, but that the code in the deployment has already seemingly fixed the problem, so people shouldn't look at the screenshots.

> Just flagging the **demo screenshots (at time of writing this comment) in the PR description** are seemingly outdated. [...] However **I do not see it in the preview deployment**

**Review by luisbettencourt — CHANGES_REQUESTED** [review]
Code LGTM. Do we also want to include an entry in the "Additional Usage" table in the pricing page for GPT-4?

**Comment by benwerner01** [comment]
> Do we also want to include an entry in the "Additional Usage" table in the pricing page for GPT-4?

Yes, thank you for spotting! I've added the items in https://github.com/blockprotocol/blockprotocol/pull/1282/commits/566352edd2df52923d1d6ae094ec772ccd07f9c5, here's what it should look like now:

https://user-images.githubusercontent.com/42802102/236177764-5e48a544-7aa2-4c53-94a1-80f45e0b8025.mov

**Comment by benwerner01** [comment]
@nonparibus just want to flag I think I've addressed all the comments you left in Vercel (not able to formally request re-review)

**Pull request merged**
