### PR TITLE
Update navbar

### PR DESCRIPTION
**Pull request by luisbettencourt**
## 🌟 What is the purpose of this PR?

This PR implements the updated design for the navbar

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203358502199087/1203800131645619/f) _(internal)_

## 🔍 What does this change?

- Icons changed;
- `Documentation` -> `Docs`;
- Spacing changed;
- Removed `Specification` navbar icon;
- Fixed issue where breadcrumbs inside a block page would be displayed under the Coming Soon banner;
- Hide Sign Up button and avatar in the account verification screen;

## 📹 Demo

image
image
image
image

Before: 

image
image

After:

image
image

### CODE REVIEW

**Comment by nonparibus** [comment]
Let's italicize `Hub` in the header (**Þ _Hub_**) per Figma. Other than that this looks good to me.

**Comment by nonparibus** [comment]
Functional UAT ✅
Still requires code review. cc @benwerner01 @CiaranMn @kachkaev

**Review by nonparibus — APPROVED** [review]
Functional UAT ✅
Still requires code review. cc @benwerner01 @CiaranMn @kachkaev

**Review by CiaranMn — CHANGES_REQUESTED** [review]
On one monitor the user's letter in the navbar appears off-centre – this can be fixed by making the span's line height the same height as the circle (i.e. `32px`) – can you add this please?

Edit to say: appreciate this might be an existing issue but worth fixing while we're updating the navbar

Screenshot 2023-01-30 at 12 00 39

Looks good otherwise!

**Review by nonparibus — APPROVED** [review]

**Review by CiaranMn — APPROVED** [review]

**Pull request merged**
